services:
  postgres-android:
    image: postgres:18.3-alpine
    container_name: postgres-android
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: cineflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_android_data:/var/lib/postgresql
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  postgres_android_data:
  minio_data:

