services:
  postgres-android:
    image: postgres:18.3-alpine
    container_name: postgres-android
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: cineflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_android_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_android_data:

